name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: "Ruby ${{ matrix.ruby-version }}: ${{ matrix.runs-on }}"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
        mysql-source-backend:
          - mysqlbinlog
          - mysql2-replication
        runs-on:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Install the latest mariadb-connector-c
        run: |
          sudo apt-get update
          sudo apt-get install -y -V \
            cmake \
            git \
            ninja-build
          git clone \
            --branch 3.2 \
            https://github.com/mariadb-corporation/mariadb-connector-c.git
          git -C mariadb-connector-c fetch origin pull/187/head:fake-rotate-event
          git -C mariadb-connector-c checkout fake-rotate-event
          git -C mariadb-connector-c rebase 3.2
          git -C mariadb-connector-c checkout -
          git -C mariadb-connector-c merge fake-rotate-event
          cmake \
            -S mariadb-connector-c \
            -B mariadb-connector-c.build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DINSTALL_LIBDIR=lib \
            -DWITH_EXTERNAL_ZLIB=ON \
            -DWITH_UNIT_TESTS=OFF
          ninja -C mariadb-connector-c.build
          sudo ninja -C mariadb-connector-c.build install
          rm -rf mariadb-connector-c*
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Test
        env:
          GROONGA_DELTA_IMPORT_MYSQL_SOURCE_BACKEND: ${{ matrix.mysql-source-backend }}
        run: |
          bundle exec ruby test/run.rb
